#! /bin/bash
# This is a simple bash script to show Raspberry Pi Status.
# v.0.71
#
# Copyright 2021 Adi_a12
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

clear
echo " NAME    : $(uname -n)"
echo " MODEL   : $(cat /sys/firmware/devicetree/base/model | tr '\0' ' ')"
echo " OS      : $(grep PRETTY_NAME /etc/os-release | cut -d \" -f 2)"
echo " KERNEL  : $(uname -r)"
echo " UPTIME  :$(uptime)"
echo " Temp    : $(vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')\" C"
echo " Internal IP    : $(ifconfig | grep broadcast |tr -s ' '| cut -d ' ' -f 3)"
echo " External IP    : $(curl -s http://checkip.dyndns.org | html2text | sed -En "s/.*Current IP Address:[^0-9]*([0-9.]+).*/\1/p")"
#echo " NodeRed: $(systemctl is-enabled nodered) $(systemctl is-active nodered)"
#echo " Mosquitto: $(systemctl is-enabled mosquitto) $(systemctl is-active mosquitto)"
